<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE chords [
	<!ELEMENT chords (chord+)>
	<!ELEMENT chord (longname,semitone+)>
	<!ELEMENT longname (#PCDATA)>
	<!ELEMENT semitone (#PCDATA)>
	<!ATTLIST chords title CDATA #IMPLIED>
	<!ATTLIST chord id ID #REQUIRED 
					name CDATA #REQUIRED>
]>

<chords title="chord numbers">
	
	<chord id="major" name="M">
	    <longname>Major triad</longname>
        <semitone>4</semitone>
        <semitone>7</semitone>
	</chord>
	<chord id="seventh" name="7">
	    <longname>Dominant seventh chord</longname>
        <semitone>4</semitone>
        <semitone>7</semitone>
        <semitone>10</semitone>
	</chord>
	<chord id="major_seventh" name="M7">
	    <longname>Major seventh chord</longname>
        <semitone>4</semitone>
        <semitone>7</semitone>
	    <semitone>11</semitone>
	</chord>
	<chord id="sixth" name="6" >
		<longname>Minor sixth chord</longname>
		<semitone>4</semitone>
        <semitone>7</semitone>
        <semitone>9</semitone>
	</chord>
	<chord id="minor" name="m" >
	    <longname>Minor triad</longname>
        <semitone>3</semitone>
        <semitone>7</semitone>
	</chord>
	<chord id="minor_major_seventh" name="mM7" >
	    <longname>Minor-major seventh chord</longname>
        <semitone>3</semitone>
        <semitone>7</semitone>
        <semitone>11</semitone>
	</chord>
	<chord id="minor_sixth" name="m6" >
	    <longname>Minor sixth chord</longname>
        <semitone>3</semitone>
        <semitone>7</semitone>
        <semitone>9</semitone>
	</chord>
	<chord id="minor_seventh" name="m7" >
  	    <longname>Minor seventh chord</longname>
        <semitone>3</semitone>
        <semitone>7</semitone>
        <semitone>10</semitone>
	</chord>
	<chord id="half_diminished_seventh" name="m7(â™­5)" >
	    <longname>Half-diminished seventh chord</longname>
        <semitone>3</semitone>
        <semitone>6</semitone>
        <semitone>10</semitone>
	</chord>
	<chord id="suspended" name="sus4" >
	    <longname>Suspended chord</longname>
        <semitone>5</semitone>
        <semitone>7</semitone>
	</chord>
	<chord id="suspendes_seventh" name="7sus4">
  	    <longname>Suspended seventh chord</longname>    
        <semitone>5</semitone>
        <semitone>7</semitone>
   	    <semitone>10</semitone>
	</chord>
	<chord id="diminished" name="dim">
	    <longname>Diminished triad</longname>
        <semitone>3</semitone>
        <semitone>6</semitone>
	</chord>
	<chord id="diminished_seventh" name="dim7">
	    <longname>Diminished seventh chord</longname>
        <semitone>3</semitone>
        <semitone>6</semitone>
        <semitone>9</semitone>
	</chord>
	<chord id="augumented" name="aug">
	    <longname>Augmented triad</longname>
        <semitone>4</semitone>
        <semitone>8</semitone>
	</chord>
	<chord id="augmented_seventh" name="aug7">
	    <longname>Augmented seventh chord</longname>
        <semitone>4</semitone>
        <semitone>8</semitone>
       	<semitone>10</semitone>
	</chord>

</chords>